keychain_name = 'fixsy.keychain'
keychain_password = 'oragonOnBoardJet21'

default_platform(:ios)

platform :ios do

  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_BASE64"],
      in_house: false,
      is_key_content_base64: true
    )
  end

  desc "Bump build number based on most recent TestFlight build number"
  lane :fetch_and_increment_build_number do |options|
    version = options[:version]
    if version
      app_store_build_number(
        live: false,
        version: version,
        initial_build_number: 1
      )
      increment_version_number(version_number: version)
      editing_version = lane_context[SharedValues::VERSION_NUMBER]
      latest_testflight_build_number(version: version)
      latest_build_number = lane_context[SharedValues::LATEST_TESTFLIGHT_BUILD_NUMBER]
      build_number = latest_build_number + 1
      increment_build_number(build_number: build_number)
      UI.message "The target version is: #{editing_version}"
      UI.message "The building version is: #{build_number}"
    else
      app_store_build_number(
        live: true,
        initial_build_number: 1
      )
      latest_version = lane_context[SharedValues::LATEST_VERSION]
      increment_version_number(version_number: latest_version)
      increment_version_number(bump_type: 'patch')
      editing_version = lane_context[SharedValues::VERSION_NUMBER]
      latest_testflight_build_number(version: editing_version)
      latest_build_number = lane_context[SharedValues::LATEST_TESTFLIGHT_BUILD_NUMBER]
      build_number = latest_build_number + 1
      increment_build_number(build_number: build_number)
      UI.message "The target version is: #{editing_version}"
      UI.message "The building version is: #{build_number}"
    end
  end
  
  desc "Build the iOS app for release"
  lane :build_release do |options|
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    build_app(
      scheme: "Fixsy_iOS PROD",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.to.fixsy" => "match AppStore com.to.fixsy",
        }
      },
      configuration: "PROD Release"
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    # deliver(
    #   submit_for_review: true,
    #   skip_metadata: true,
    #   skip_screenshots: true,
    #   skip_binary_upload: true
    # )
    upload_to_testflight(
      username: "tylerlantern@gmail.com",
      skip_submission: true
    )
  end


  desc "Manual code signing"
  lane :manual_code_signing do
    UI.message "CODE SIGNING"
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "./Fixsy.xcodeproj"
    )
    # release
  end


  desc "MATCH AND INSTALL CERTIFICATION"
  lane :match_development do
    match(
      type: "development",
      app_identifier: ["com.to.fixsy.dev"]
    )

  end

  desc "MATCH AND INSTALL CERTIFICATION"
  lane :match_cert do
    # match
    match(
      type: "appstore",
      app_identifier: 'com.to.fixsy'
    )

    # create_keychain(
    #   name: keychain_name,
    #   password: keychain_password,
    #   default_keychain: true,
    #   unlock: true,
    #   timeout: 360000,
    #   lock_when_sleeps: false,
    #   add_to_search_list: true
    # )
    
    # match(
    #   type: "appstore",
    #   app_identifier: 'com.to.fixsy'
      # keychain_name: keychain_name,
      # keychain_password: keychain_password,
    # )
    # provisioning_profile_path = ENV["sigh_com.to.fixsy_appstore_profile-name"]

    # provisioning_profile_path = ENV["sigh_com.to.fixsy_appstore_profile-path"]
    # sigh_com.to.fixsy_appstore_profile-path 
    # sh "open \"#{provisioning_profile_path}\""
    # install_provisioning_profile(path: "#{provisioning_profile_path}")

  end

  desc "Build and upload to TestFlight"
  lane :build_upload_testflight do |options|
    UI.message "The TAKE is: #{ENV["ASC_KEY_ID"]}"
    load_asc_api_key
    fetch_and_increment_build_number version:options[:version]
    match_cert
    build_release
    release
  end

  desc "Build and upload to TestFlight"
  lane :test_deliver do
    # load_asc_api_key
    # fetch_and_increment_build_number
    # match
    # build_release
  end
end
